dist: bionic
language: c

addons:
  apt:
    packages:
    - device-tree-compiler
    - gcc-arm-linux-gnueabihf
    - gcc-aarch64-linux-gnu

script:
- make
- make show

deploy:
  provider: releases
  api_key:
    secure: "xcVagnT/EK6gTEsSdEI3z6V7LS23dW2r7slFGN/+K/NUFS5yVLJnOyDrjY+TKlud/n2W5jBkC0yu3AlZTdIaYoTO67YN+RBdK9vHYhin0Utc4c6UKNUqu39VIVYQELJwDCQv9pMfYu2kAL8nfk7IKWIog31on7fkumMCZuSDmnL7v2nMdNOUpp1wZerf509uBAS9vApMUHtj/rHdVlVXw+okSifJp+IbRZpFbZEOuwRJ6HPjgfWNHtOALrNt80PWHBXNnbNWccLzGby0YW7ZxsCtmm8IxCB0ItAKWzZqIW3eiUd3NzBvI3s/yqwdGbah0bPaC8hyVfK4XI29ouH8a1utdM2uVHRVINNDCY3u0DkDyW0dECEb9gKOwGDZtmsGn+dh0fHhFgabh+6Xm46TrdCT4UCI2N2PFDKESBX8Bam9LZsCOts/CgP8GyPx/on8Hzan2ezI/ecs4Rvu/mIUAu9W1/k/xOVH2BO+M91cIPFhzo25qrG++VByX3moo8NydFSveAgeAdOORUF6WKaIrsV8VHbMEV11Xk53KwOHzaqXlf1GY8KMcDTk+35ZECpHBJ2j2LMCkxJxZiQt4xUNwg/vth8BCTdj2lLA6kQc9pkz6eWg6uS2Kq/1qgL9jutPsCQsCUwaR92Rr/rhbSTyT6VqbDUkRpHroGPxAnaXXX0="
  file_glob: true
  file:
  - "*.bin"
  - "*.dtb"
  - "MD5SUMS"
  - "SHA1SUMS"
  - "SHA256SUMS"
  - "SHA512SUMS"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
