dist: bionic
language: c

addons:
  apt:
    packages:
    - device-tree-compiler
    - gcc-arm-linux-gnueabihf
    - gcc-aarch64-linux-gnu

script:
- make
- make show

deploy:
  provider: releases
  api_key:
    secure: EHsjoG43vAM+0tB/15osuy6qlEgntX8IBRQYJeSEeOegWyJ2fS1fPhy/b4tZCGV0Dzz7dQpP869njEv8wlIlyMnz8xqNZkbgzjk0oUQ2IvAovAHwi5rzKPGpoEhXZ0QxCkumGCLLPERTLY6fcIgMxatGIbTPijOB+Vbk3yC40BsBHH/yd3jpkk1zRjZg0pQBdghVhmJqF6KbH93OqDbWBa32oVe+X8FMi5V9+kCQUSDC+FGz1asvHHexhcaeWySa6ZkEx9jIFcp6ViHP6aGztDHv+rUhpC5YsWd/lgLubOzNorQKAa6TqE0iCYLCNINqeINo+32NW5ZOOFvBoleou/afgqi5zinpdumzGnLtLH7an5TrbAQ6XjA0vsK2o68x5EXNqS71V6bfYRFWzWetrDWV87H8NPP4H7j8WEZwZ7938iMPcW/mkZQI5n0diGzvZ9WA8aAdP9JVaMzmg9q84jeYqAI3BhqClmc+THlfu14nD1CEEYJERta4NhZLicbwgVbnGpGaoFCm01NYa7ukDfCC6IbQGjZoBk0Btl3rg6KUtfTRCDjtG336PuBWAhBjzBzTKdG4uJ6/9kj4dE2+FbrpshL55s8K2kfrpoYUPQEBVjHHUOYzmMDWE9sG7OsIeoYeGTINu7VPjF4gAiBZzPIdqCGyrCbh5Gy+iPCl6Hg=
  file_glob: true
  file:
  - *.bin
  - *.dtb
  - MD5SUMS
  - SHA1SUMS
  - SHA256SUMS
  - SHA512SUMS
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
