dist: bionic
language: c

addons:
  apt:
    packages:
    - device-tree-compiler
    - gcc-arm-linux-gnueabihf
    - gcc-aarch64-linux-gnu

env:
  global:
  - BUILD_DIR="/tmp/uboot-rpi"

script:
- make
- make show

deploy:
  provider: releases
  api_key:
    secure: "yTInS42GLG3tb0M91yK1Zgo69Q78KQWzeUgFBGVaDSDWZolSkycDY2uUBTXSDU5pxW7hkhasDaISgcmD+UrcvfZQBnFcgVw0iRC/GLDSB+l6UV07Mf9nUUk6zuzDsBcEUsNlOJpCCCH4zQYlywryiuhpW/Ic3IleI6bZkiRjD9i9XZbtduecCUsI4acFplz/3NgHztRyHmQcpoz18Ze471eJqOECnywgAJK8v5hE7Y6t8bVO+rCECM37/8IpRlcBwjm6zamK7NBQeJLMzUIj46hpeXut/t97JQLLOUIuw1y+fSkBVmlYPh0by/5fxAmQ9mWn5N0UQML/29n7Sg0VLwDwNe3gXIphzcGhy41lVXtXSaTq9s0mJaDsIKHYKISUz3iydD2oqXf6BvRh23Ft9mYuYtW2TZdFc9XbkvTwcpjqwb7tzK43UO/Vut18u7EIGWw3sIu1Ce9BUGIruQphN8Nc/Wrs2oJuCvJpsus2pnIWSv+l7tFPFN03AY5o77njVQaXl34YIJuzP4IXZcGVNRjjHGzfc/rKF2+RgEb/r21YUu33VN0FV/2+ZW7KkwRWgaKGyyD5ar1RbMY2y9cJ7iQ6xEMVCmygnRqJ9Uj4fFzisbSzVo/fGXsnJMwvNUdLp3vLCEKtB5m/DKxuFnm0OkYMBBijmIthkme4uHWaWik="
  file_glob: true
  file:
  - "*.bin"
  - "MD5SUMS"
  - "SHA1SUMS"
  - "SHA256SUMS"
  - "SHA512SUMS"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
